Obooking/Controllers/mainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Obooking.Models;
using Obooking.MyClasses;

namespace Obooking.Controllers
{
    public class mainController : Controller
    {
        public ApplicationDbContext _context;
        MySession session;
        public mainController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
        // GET: main
        public ActionResult Showmain(String sortOrder,string searchString)
        {
            ViewData["PopularitySortParam"] = String.IsNullOrEmpty(sortOrder) ? "Popularity_asce" : "";
            ViewData["currentFilter"] = searchString;
            var books = from x in _context.Books_table select x;

            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(x => x.BookCategory == searchString);
            }

            switch (sortOrder)
            {
                case "Popularity_asce":
                    books = books.OrderBy(x => x.BookPopularity);
                    break;

                default:
                    break;
            }
            return View(books.ToList());
        }

        public ActionResult ViewReview(int id)
        {
          //  var reviews = _context.Review_table.Where(x => x.bookid == id).ToList();

            var review = _context.Review_table.ToList();
            var user = _context.my_users.ToList();
            var book = _context.Books_table.ToList();

            var output = from r in review
                         join u in user on r.userid equals u.id
                         join b in book on r.Book_Name equals b.BookName
                         where b.BookId == id
                         select new ReviewVM
                         {
                             book = b,
                             review = r,
                             user = u
                         };


            return View(output);
        }

        [HttpGet]
        public ActionResult Review()
        {
            session = MySession.Instance;
            var order = _context.Order_table.ToList();
            var order_details = _context.OrderDetails_table.ToList();
            var book = _context.Books_table.ToList();
            var output = from o in order
                         join d in order_details on o.ID equals d.OrderID
                         join b in book on d.BookID equals b.BookId
                         where o.UserName == session.username && d.status == "sold"
                         select new Cart
                         {
                             book = b,
                             order = o,
                             orderDetails = d
                         };
            ///
            var books_name = new List<string>();
            foreach (var item in output)
                books_name.Add(item.book.BookName);
            ViewBag.BooksNames = new SelectList(books_name);

            if (books_name.Count == 0)
            {
                ViewBag.check = "you have to pursher anybook";
            }
            else
            {

                ViewBag.check = "Select Your book...";
            }

            return View();
        }

        [HttpPost]
        public ActionResult Review(Review rev)
        {
            session = MySession.Instance;
            var order = _context.Order_table.ToList();
            var order_details = _context.OrderDetails_table.ToList();
            var book = _context.Books_table.ToList();
            var output = from o in order
                         join d in order_details on o.ID equals d.OrderID
                         join b in book on d.BookID equals b.BookId
                         where o.UserName == session.username && d.status == "sold"
                         select new Cart
                         {
                             book = b,
                             order = o,
                             orderDetails = d
                         };
            ///
            var books_name = new List<string>();
            foreach (var item in output)
                books_name.Add(item.book.BookName);
            ViewBag.BooksNames = new SelectList(books_name);
            if (books_name.Count == 0)
            {
                ViewBag.check = "you have to pursher anybook";
            }
            else
            {

                ViewBag.check = "Select Your book...";
            }
            rev.userid = session.id;
            _context.Review_table.Add(rev);
            _context.SaveChanges();
            return View();
        }
    }
}

Obooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online Booking", "Showmain", "main",new { area = "" }, new { @class = "navbar-brand" } )
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Showmain", "main")</li>
                    <li>@Html.ActionLink("Add Review", "Review", "main")</li>
                    <li>@Html.ActionLink("My Order Status", "OrderStatus", "Order")</li>
                    <li>@Html.ActionLink("Previous Orders", "PrevOrders", "Order")</li>
                    <li>@Html.ActionLink("Payment Page", "Payment", "Order")</li>
                    <li style="margin-left:300px;">@Html.ActionLink("Log out", "login", "user")</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Obooking/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>
             
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>